### ISSUE TITLE
Objects rendering white

### ISSUE THREAD

**Issue by mkolar** [Gael-Honorez-sb/abctoa#10]
Hi.

We've tried the latest compiled version for mtoa 2.1.0.1.

Plugins seem to load correctly, we can work with the caches and shader manager, however when we assign shaders, the object still renders with the default white material. Is there something we might have overlooked that needs to be set up on top of loading the module?

Cheers

**Comment by LichiMan** [comment]
Hi,

AbcToA 3.0.1 is still using Shading Groups to assign shaders. That's something that MtoA doesn't use it anymore. 

As a workaround you can enable the "Export Shading Engine (Legacy)" option inside the Render Settings in the System tab.

Cheers.

**Comment by mkolar** [comment]
Brilliant. that works (I just assumed that the last patch for 2.1 was changing that).

Thank you.
