### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by ghost** [Gael-Honorez-sb/abctoa#4]
Hi Gael,

I'm having issues building this. Tried a bunch of things but nothing seems to work. This is what I'm running right now:

`cmake -DBOOST_ROOT=/repo/boost-1.55.0 -DINSTALL_DIR=${PWD}/install -DPYSTRING_LIBRARY=/repo/libs/lib/libpystring.so -DPYSTRING_INCLUDE_DIR=/repo/libs/include -DPYSTRING_DIR=/repo/libs/lib -DILMBASE_ROOT=/repo/libs/ilmbase-2.0.1 -DALEMBIC_DIR=/repo/libs/alembic/1.5.0.21 -DMTOA_LIBRARY=/repo/apps/SolidAngle/mtoadeploy/1.4.2.2/2017/bin/libmtoa_api.so -DMTOA_INCLUDE_DIR=/repo/apps/SolidAngle/mtoadeploy/1.4.2.2/2017/include -DARNOLD_BASE_DIR=/repo/apps/SolidAngle/core/Arnold-4.2.16.2-linux -DJSONCPP_LIBRARY=/repo/libs/lib/libjsoncpp.so -DJSONCPP_INCLUDE_DIR=/repo/libs/include -DARNOLD_INCLUDE_DIR=/repo/apps/SolidAngle/core/Arnold-4.2.16.2-linux/include -DARNOLD_LIBRARY=/repo/apps/SolidAngle/core/Arnold-4.2.16.2-linux/bin/libai.so`

I had to provide the complete .so path for the arnold and other libs as cmake did not seem to pick up the full libs path and was instead sending the lib directory to the linker which resulted in errors. This generates the makefile but when I run make it fails at this step:

```
[  1%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WritePoint.cpp.o
[  3%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/SampleUtil.cpp.o
[  4%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WriteCamera.cpp.o
[  6%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/ProcMain.cpp.o
[  8%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WriteCurves.cpp.o
[  9%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WriteGeo.cpp.o
[ 11%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WriteTransform.cpp.o
[ 12%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WriteOverrides.cpp.o
[ 14%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/getBounds.cpp.o
[ 16%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/ArbGeomParams.cpp.o
[ 17%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/ReadInstancer.cpp.o
[ 19%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/WriteLight.cpp.o
[ 20%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/parseAttributes.cpp.o
[ 22%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/ProcArgs.cpp.o
[ 24%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/NodeCache.cpp.o
[ 25%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/__/__/__/common/abcshaderutils.cpp.o
[ 27%] Building CXX object arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/__/__/__/common/PathUtil.cpp.o
make[2]: *** No rule to make target `contrib/install/usr/local/include/lib/libjsoncpp.so', needed by `arnold/procedurals/alembicProcedural/arnoldAlembicProcedural.so'.  Stop.
make[1]: *** [arnold/procedurals/alembicProcedural/CMakeFiles/arnoldAlembicProcedural.dir/all] Error 2
make: *** [all] Error 2
```
Can you please help me debug this? I'm not sure why its using the jsoncpp as the target rule so most likely something in the cmake step is garbled. This is the platform right now:

CentOS 6.4
gcc 4.8.2
Maya 2017 Update 3
MtoA 1.4.2.2
Arnold Core 4.2.16.2
Alembic 1.5.0.21
Boost 1.55.0
jsoncpp 1.6.5

Thanks,
Sachin

**Comment by Gael-Honorez-sb** [comment]
The whole build process has been updated for maya > 2017 and mtoa > 2.0
